server:
  port: 80

spring:
    datasource:
      name: mydb
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:mysql://13.58.247.105:3306/EXHUB_EXCHANGE?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20

    thymeleaf:
            prefix: classpath:templates/

mybatis:
    mapperLocations: classpath:mapper/*.xml
    typeAliasesPackage: io.exhub.exhub_manager.pojo.DO
    configuration:
      map-underscore-to-camel-case: true

exhubConfig:
  managerSession: managerUser
  registerPoint: 100
  peopleCount: 10000
  extraPoint: 500
  referrerPoint: 88
  # 发送者邮箱
  fromEmail: Bilala<info@bilala.io>
  # 身份认证通过通知
  identityAuthSuccess: email/identity-auth-success
  # 身份认证失败通知
  identityAuthFail: email/identity-auth-fail

logging:
  level:
    io.exhub.exhub_manager.controller: debug
    io.exhub.exhub_manager.mapper: debug